# Generated by Django 6.0.2 on 2026-08-28 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
        ('catalog', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('on_hand_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_counted_at', models.DateField(blank=True, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.variant')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, choices=[('STOCK_INITIAL', 'Stock initial (création produit)'), ('COMMANDE_LIVREE', 'Commande livrée'), ('ACHAT_FOURNISSEUR', 'Achat fournisseur'), ('RETOUR_TEST', 'Retour de test'), ('CORRECTION_INVENTAIRE', 'Correction inventaire'), ('CADEAU_PROMO', 'Cadeau/Promotion'), ('VENTE', 'Vente'), ('SORTIE_MAGASIN', 'Sortie magasin'), ('CASSE_PERTE', 'Casse/Perte'), ('ECHANTILLON', 'Échantillon'), ('INVENTAIRE_ANNUEL', 'Inventaire annuel'), ('CORRECTION_MANUELLE', 'Correction manuelle'), ('PEREMPTION', 'Péremption'), ('RETOUR_CLIENT', 'Retour client'), ('REMBOURSEMENT', 'Remboursement'), ('AUTRE', 'Autre')], max_length=32, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='boutiques.boutique')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='catalog.product')),
                ('purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchases.purchaseline')),
                ('sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.saleline')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stock')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'stockmovement',
                'ordering': ['-created_at'],
            },
        ),
    ]
