# Generated by Django 6.0.2 on 2026-09-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='model',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
    ]
