# Generated by Django 6.0.2 on 2026-08-28 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(blank=True, max_length=150)),
                ('theme_primary_color', models.CharField(default='#0f172a', max_length=7)),
                ('theme_accent_color', models.CharField(default='#f59e0b', max_length=7)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('enabled_features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boutiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoutiqueSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('critical_stock_threshold', models.IntegerField(default=5)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_system_updates', models.BooleanField(default=True)),
                ('notify_weekly_report', models.BooleanField(default=True)),
                ('boutique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Réglages boutique',
                'verbose_name_plural': 'Réglages boutique',
                'db_table': 'boutiquesettings',
            },
        ),
    ]
