# Generated by Django 6.0.2 on 2026-08-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
