# Generated by Django 6.0.2 on 2026-09-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_boutique_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='variant_attributes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
