# Generated by Django 6.0.2 on 2026-08-28 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'customer',
                'constraints': [models.UniqueConstraint(fields=('boutique', 'phone'), name='unique_customer_phone_per_boutique')],
            },
        ),
    ]
