# Generated by Django 6.0.2 on 2026-08-28 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('total_variantes', models.IntegerField(default=0)),
                ('quantite_comptee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='boutiques.boutique')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'db_table': 'inventorycount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_or_updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorycount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lines', to='catalog.variant')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'db_table': 'inventoryline',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('inventory_count', 'variant'), name='unique_variant_per_inventory_count')],
            },
        ),
    ]
