# Generated by Django 6.0.2 on 2026-08-28 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('store', 'Boutique'), ('en_ligne', 'En ligne')], default='store', max_length=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('credit', 'Crédit (ardoise)')], default='cash', max_length=20)),
                ('mobile_money_reference', models.CharField(blank=True, max_length=100)),
                ('mobile_money_sender', models.CharField(blank=True, max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PAYE', 'Payé'), ('NONPAYE', 'Non payé'), ('PARTIEL', 'Partiel'), ('REMBOURSE', 'Remboursé')], default='NONPAYE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='boutiques.boutique')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'sale',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='catalog.variant')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'db_table': 'saleline',
            },
        ),
    ]
