# Generated by Django 6.0.2 on 2026-08-28 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_label', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('unjustified_absences', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Partiel'), ('paye', 'Payé')], default='non_paye', max_length=10)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='boutiques.boutique')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_label'), name='unique_payroll_entry_per_period')],
            },
        ),
    ]
