# Generated by Django 6.0.2 on 2026-08-28 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('access_role', models.CharField(choices=[('gerant', 'Gérant'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('allowed_pages', models.JSONField(blank=True, default=list)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='boutiques.boutique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil employé',
                'verbose_name_plural': 'Profils employés',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('retard', 'Retard'), ('absence', 'Absence')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('actual_time', models.TimeField(blank=True, null=True)),
                ('justified', models.BooleanField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='boutiques.boutique')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
            },
        ),
    ]
